### ISSUE TITLE
Seminario1-revGladimir

### ISSUE THREAD

**Issue by gladimircc** [LaudrinGarralaga/Hora-Marcada#1]
- [x] Cobrar antecipadamente e online uma taxa para marcar o horário. Quando o usuário comparecer à quadra e for atendido, o valor da taxa será descontado do valor do serviço.

**Comment by LaudrinGarralaga** [comment]
Foi discutido com o orientador esta possibilidade, mas achamos melhor desenvolver um "sistema de pontos", onde o cliente vai adquirindo pontos ao confirmar a reserva, confirmando 12 reservas ele adquiri 12 pontos e como recompensa ganha uma reserva grátis, caso ele cancele o horário ele perde 1 ponto. Achamos melhor este sistema, pois quem reserva depende dos seus convidados e caso eles não compareçam que pagou a taxa adiantada perde o valor, com o sistema de pontos achamos que fica mais justo.
