### ISSUE TITLE
BancaFinal - revLuzzardi

### ISSUE THREAD

**Issue by pluzzardi** [LaudrinGarralaga/Hora-Marcada#3]
1. Cuidado, não abreviar: Cr. de grupos

2. Melhorar a Motivação e Justificativa

3. Legal, bem descrito e bem detalhado

4. Erro de digitação no aplicativo "Bem vido"

5. O aplicativo poderia estar mais adiantado, por  causa das reservas, que não é simples

6. Porque "Enviar" e não "Gravar"?

7.

**Comment by LaudrinGarralaga** [comment]
As devidas correções já foram feitas.
