### ISSUE TITLE
Seminário2_revDartagnan

### ISSUE THREAD

**Issue by ddfarias** [LaudrinGarralaga/Hora-Marcada#6]
* Implementar login com rede social
* Corrigir erro de português no artigo "Conciderações".
* Para o seminário final, demonstrar o funcionamento do sistema.
* Detalhar melhor com o orientador o que/como (funções do sistema) será mostrado na apresentação.

**Comment by LaudrinGarralaga** [comment]
- O login por rede social poderá ser implementado no futuro.
- Erro já corrigido.
- Será mostrado melhor o funcionamento do sistema na banca final.
